
package net.felsing.client_cert.ejbca;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.2
 * 2017-05-15T16:18:08.024+02:00
 * Generated source version: 3.1.2
 */

@WebFault(name = "AlreadyRevokedException", targetNamespace = "http://ws.protocol.core.ejbca.org/")
public class AlreadyRevokedException_Exception extends Exception {
    
    private net.felsing.client_cert.ejbca.AlreadyRevokedException alreadyRevokedException;

    public AlreadyRevokedException_Exception() {
        super();
    }
    
    public AlreadyRevokedException_Exception(String message) {
        super(message);
    }
    
    public AlreadyRevokedException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public AlreadyRevokedException_Exception(String message, net.felsing.client_cert.ejbca.AlreadyRevokedException alreadyRevokedException) {
        super(message);
        this.alreadyRevokedException = alreadyRevokedException;
    }

    public AlreadyRevokedException_Exception(String message, net.felsing.client_cert.ejbca.AlreadyRevokedException alreadyRevokedException, Throwable cause) {
        super(message, cause);
        this.alreadyRevokedException = alreadyRevokedException;
    }

    public net.felsing.client_cert.ejbca.AlreadyRevokedException getFaultInfo() {
        return this.alreadyRevokedException;
    }
}
