
package net.felsing.client_cert.ejbca;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.2
 * 2017-05-15T16:18:07.997+02:00
 * Generated source version: 3.1.2
 */

@WebFault(name = "ApprovalRequestExpiredException", targetNamespace = "http://ws.protocol.core.ejbca.org/")
public class ApprovalRequestExpiredException_Exception extends Exception {
    
    private net.felsing.client_cert.ejbca.ApprovalRequestExpiredException approvalRequestExpiredException;

    public ApprovalRequestExpiredException_Exception() {
        super();
    }
    
    public ApprovalRequestExpiredException_Exception(String message) {
        super(message);
    }
    
    public ApprovalRequestExpiredException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public ApprovalRequestExpiredException_Exception(String message, net.felsing.client_cert.ejbca.ApprovalRequestExpiredException approvalRequestExpiredException) {
        super(message);
        this.approvalRequestExpiredException = approvalRequestExpiredException;
    }

    public ApprovalRequestExpiredException_Exception(String message, net.felsing.client_cert.ejbca.ApprovalRequestExpiredException approvalRequestExpiredException, Throwable cause) {
        super(message, cause);
        this.approvalRequestExpiredException = approvalRequestExpiredException;
    }

    public net.felsing.client_cert.ejbca.ApprovalRequestExpiredException getFaultInfo() {
        return this.approvalRequestExpiredException;
    }
}
