
package net.felsing.client_cert.ejbca;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.2
 * 2015-08-25T09:25:39.336+02:00
 * Generated source version: 3.1.2
 */

@WebFault(name = "ApprovalRequestExecutionException", targetNamespace = "http://ws.protocol.core.ejbca.org/")
public class ApprovalRequestExecutionException_Exception extends Exception {
    
    private net.felsing.client_cert.ejbca.ApprovalRequestExecutionException approvalRequestExecutionException;

    public ApprovalRequestExecutionException_Exception() {
        super();
    }
    
    public ApprovalRequestExecutionException_Exception(String message) {
        super(message);
    }
    
    public ApprovalRequestExecutionException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public ApprovalRequestExecutionException_Exception(String message, net.felsing.client_cert.ejbca.ApprovalRequestExecutionException approvalRequestExecutionException) {
        super(message);
        this.approvalRequestExecutionException = approvalRequestExecutionException;
    }

    public ApprovalRequestExecutionException_Exception(String message, net.felsing.client_cert.ejbca.ApprovalRequestExecutionException approvalRequestExecutionException, Throwable cause) {
        super(message, cause);
        this.approvalRequestExecutionException = approvalRequestExecutionException;
    }

    public net.felsing.client_cert.ejbca.ApprovalRequestExecutionException getFaultInfo() {
        return this.approvalRequestExecutionException;
    }
}
