
package net.felsing.client_cert.ejbca;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.2
 * 2015-12-27T19:07:25.553+01:00
 * Generated source version: 3.1.2
 */

@WebFault(name = "AuthorizationDeniedException", targetNamespace = "http://ws.protocol.core.ejbca.org/")
public class AuthorizationDeniedException_Exception extends Exception {
    
    private net.felsing.client_cert.ejbca.AuthorizationDeniedException authorizationDeniedException;

    public AuthorizationDeniedException_Exception() {
        super();
    }
    
    public AuthorizationDeniedException_Exception(String message) {
        super(message);
    }
    
    public AuthorizationDeniedException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public AuthorizationDeniedException_Exception(String message, net.felsing.client_cert.ejbca.AuthorizationDeniedException authorizationDeniedException) {
        super(message);
        this.authorizationDeniedException = authorizationDeniedException;
    }

    public AuthorizationDeniedException_Exception(String message, net.felsing.client_cert.ejbca.AuthorizationDeniedException authorizationDeniedException, Throwable cause) {
        super(message, cause);
        this.authorizationDeniedException = authorizationDeniedException;
    }

    public net.felsing.client_cert.ejbca.AuthorizationDeniedException getFaultInfo() {
        return this.authorizationDeniedException;
    }
}
