
package net.felsing.client_cert.ejbca;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.2
 * 2017-05-15T16:18:08+02:00
 * Generated source version: 3.1.2
 */

@WebFault(name = "CADoesntExistsException", targetNamespace = "http://ws.protocol.core.ejbca.org/")
public class CADoesntExistsException_Exception extends Exception {
    
    private net.felsing.client_cert.ejbca.CADoesntExistsException caDoesntExistsException;

    public CADoesntExistsException_Exception() {
        super();
    }
    
    public CADoesntExistsException_Exception(String message) {
        super(message);
    }
    
    public CADoesntExistsException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public CADoesntExistsException_Exception(String message, net.felsing.client_cert.ejbca.CADoesntExistsException caDoesntExistsException) {
        super(message);
        this.caDoesntExistsException = caDoesntExistsException;
    }

    public CADoesntExistsException_Exception(String message, net.felsing.client_cert.ejbca.CADoesntExistsException caDoesntExistsException, Throwable cause) {
        super(message, cause);
        this.caDoesntExistsException = caDoesntExistsException;
    }

    public net.felsing.client_cert.ejbca.CADoesntExistsException getFaultInfo() {
        return this.caDoesntExistsException;
    }
}
