
package net.felsing.client_cert.ejbca;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.2
 * 2015-12-27T19:07:25.578+01:00
 * Generated source version: 3.1.2
 */

@WebFault(name = "CAOfflineException", targetNamespace = "http://ws.protocol.core.ejbca.org/")
public class CAOfflineException_Exception extends Exception {
    
    private net.felsing.client_cert.ejbca.CAOfflineException caOfflineException;

    public CAOfflineException_Exception() {
        super();
    }
    
    public CAOfflineException_Exception(String message) {
        super(message);
    }
    
    public CAOfflineException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public CAOfflineException_Exception(String message, net.felsing.client_cert.ejbca.CAOfflineException caOfflineException) {
        super(message);
        this.caOfflineException = caOfflineException;
    }

    public CAOfflineException_Exception(String message, net.felsing.client_cert.ejbca.CAOfflineException caOfflineException, Throwable cause) {
        super(message, cause);
        this.caOfflineException = caOfflineException;
    }

    public net.felsing.client_cert.ejbca.CAOfflineException getFaultInfo() {
        return this.caOfflineException;
    }
}
