
package net.felsing.client_cert.ejbca;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.2
 * 2015-08-25T09:25:39.387+02:00
 * Generated source version: 3.1.2
 */

@WebFault(name = "CertificateExpiredException", targetNamespace = "http://ws.protocol.core.ejbca.org/")
public class CertificateExpiredException_Exception extends Exception {
    
    private net.felsing.client_cert.ejbca.CertificateExpiredException certificateExpiredException;

    public CertificateExpiredException_Exception() {
        super();
    }
    
    public CertificateExpiredException_Exception(String message) {
        super(message);
    }
    
    public CertificateExpiredException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public CertificateExpiredException_Exception(String message, net.felsing.client_cert.ejbca.CertificateExpiredException certificateExpiredException) {
        super(message);
        this.certificateExpiredException = certificateExpiredException;
    }

    public CertificateExpiredException_Exception(String message, net.felsing.client_cert.ejbca.CertificateExpiredException certificateExpiredException, Throwable cause) {
        super(message, cause);
        this.certificateExpiredException = certificateExpiredException;
    }

    public net.felsing.client_cert.ejbca.CertificateExpiredException getFaultInfo() {
        return this.certificateExpiredException;
    }
}
