
package net.felsing.client_cert.ejbca;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.2
 * 2015-08-25T09:25:39.346+02:00
 * Generated source version: 3.1.2
 */

@WebFault(name = "CesecoreException", targetNamespace = "http://ws.protocol.core.ejbca.org/")
public class CesecoreException_Exception extends Exception {
    
    private net.felsing.client_cert.ejbca.CesecoreException cesecoreException;

    public CesecoreException_Exception() {
        super();
    }
    
    public CesecoreException_Exception(String message) {
        super(message);
    }
    
    public CesecoreException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public CesecoreException_Exception(String message, net.felsing.client_cert.ejbca.CesecoreException cesecoreException) {
        super(message);
        this.cesecoreException = cesecoreException;
    }

    public CesecoreException_Exception(String message, net.felsing.client_cert.ejbca.CesecoreException cesecoreException, Throwable cause) {
        super(message, cause);
        this.cesecoreException = cesecoreException;
    }

    public net.felsing.client_cert.ejbca.CesecoreException getFaultInfo() {
        return this.cesecoreException;
    }
}
