
package net.felsing.client_cert.ejbca;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.2
 * 2015-08-25T09:25:39.357+02:00
 * Generated source version: 3.1.2
 */

@WebFault(name = "EndEntityProfileNotFoundException", targetNamespace = "http://ws.protocol.core.ejbca.org/")
public class EndEntityProfileNotFoundException_Exception extends Exception {
    
    private net.felsing.client_cert.ejbca.EndEntityProfileNotFoundException endEntityProfileNotFoundException;

    public EndEntityProfileNotFoundException_Exception() {
        super();
    }
    
    public EndEntityProfileNotFoundException_Exception(String message) {
        super(message);
    }
    
    public EndEntityProfileNotFoundException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public EndEntityProfileNotFoundException_Exception(String message, net.felsing.client_cert.ejbca.EndEntityProfileNotFoundException endEntityProfileNotFoundException) {
        super(message);
        this.endEntityProfileNotFoundException = endEntityProfileNotFoundException;
    }

    public EndEntityProfileNotFoundException_Exception(String message, net.felsing.client_cert.ejbca.EndEntityProfileNotFoundException endEntityProfileNotFoundException, Throwable cause) {
        super(message, cause);
        this.endEntityProfileNotFoundException = endEntityProfileNotFoundException;
    }

    public net.felsing.client_cert.ejbca.EndEntityProfileNotFoundException getFaultInfo() {
        return this.endEntityProfileNotFoundException;
    }
}
