
package net.felsing.client_cert.ejbca;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.2
 * 2017-05-15T16:18:07.995+02:00
 * Generated source version: 3.1.2
 */

@WebFault(name = "HardTokenDoesntExistsException", targetNamespace = "http://ws.protocol.core.ejbca.org/")
public class HardTokenDoesntExistsException_Exception extends Exception {
    
    private net.felsing.client_cert.ejbca.HardTokenDoesntExistsException hardTokenDoesntExistsException;

    public HardTokenDoesntExistsException_Exception() {
        super();
    }
    
    public HardTokenDoesntExistsException_Exception(String message) {
        super(message);
    }
    
    public HardTokenDoesntExistsException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public HardTokenDoesntExistsException_Exception(String message, net.felsing.client_cert.ejbca.HardTokenDoesntExistsException hardTokenDoesntExistsException) {
        super(message);
        this.hardTokenDoesntExistsException = hardTokenDoesntExistsException;
    }

    public HardTokenDoesntExistsException_Exception(String message, net.felsing.client_cert.ejbca.HardTokenDoesntExistsException hardTokenDoesntExistsException, Throwable cause) {
        super(message, cause);
        this.hardTokenDoesntExistsException = hardTokenDoesntExistsException;
    }

    public net.felsing.client_cert.ejbca.HardTokenDoesntExistsException getFaultInfo() {
        return this.hardTokenDoesntExistsException;
    }
}
