
package net.felsing.client_cert.ejbca;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.2
 * 2015-08-25T09:25:39.311+02:00
 * Generated source version: 3.1.2
 */

@WebFault(name = "NotFoundException", targetNamespace = "http://ws.protocol.core.ejbca.org/")
public class NotFoundException_Exception extends Exception {
    
    private net.felsing.client_cert.ejbca.NotFoundException notFoundException;

    public NotFoundException_Exception() {
        super();
    }
    
    public NotFoundException_Exception(String message) {
        super(message);
    }
    
    public NotFoundException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public NotFoundException_Exception(String message, net.felsing.client_cert.ejbca.NotFoundException notFoundException) {
        super(message);
        this.notFoundException = notFoundException;
    }

    public NotFoundException_Exception(String message, net.felsing.client_cert.ejbca.NotFoundException notFoundException, Throwable cause) {
        super(message, cause);
        this.notFoundException = notFoundException;
    }

    public net.felsing.client_cert.ejbca.NotFoundException getFaultInfo() {
        return this.notFoundException;
    }
}
