
package net.felsing.client_cert.ejbca;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.2
 * 2017-05-15T16:18:08.033+02:00
 * Generated source version: 3.1.2
 */

@WebFault(name = "PublisherException", targetNamespace = "http://ws.protocol.core.ejbca.org/")
public class PublisherException_Exception extends Exception {
    
    private net.felsing.client_cert.ejbca.PublisherException publisherException;

    public PublisherException_Exception() {
        super();
    }
    
    public PublisherException_Exception(String message) {
        super(message);
    }
    
    public PublisherException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public PublisherException_Exception(String message, net.felsing.client_cert.ejbca.PublisherException publisherException) {
        super(message);
        this.publisherException = publisherException;
    }

    public PublisherException_Exception(String message, net.felsing.client_cert.ejbca.PublisherException publisherException, Throwable cause) {
        super(message, cause);
        this.publisherException = publisherException;
    }

    public net.felsing.client_cert.ejbca.PublisherException getFaultInfo() {
        return this.publisherException;
    }
}
