
package net.felsing.client_cert.ejbca;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.2
 * 2015-12-27T19:07:25.617+01:00
 * Generated source version: 3.1.2
 */

@WebFault(name = "SignRequestException", targetNamespace = "http://ws.protocol.core.ejbca.org/")
public class SignRequestException_Exception extends Exception {
    
    private net.felsing.client_cert.ejbca.SignRequestException signRequestException;

    public SignRequestException_Exception() {
        super();
    }
    
    public SignRequestException_Exception(String message) {
        super(message);
    }
    
    public SignRequestException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public SignRequestException_Exception(String message, net.felsing.client_cert.ejbca.SignRequestException signRequestException) {
        super(message);
        this.signRequestException = signRequestException;
    }

    public SignRequestException_Exception(String message, net.felsing.client_cert.ejbca.SignRequestException signRequestException, Throwable cause) {
        super(message, cause);
        this.signRequestException = signRequestException;
    }

    public net.felsing.client_cert.ejbca.SignRequestException getFaultInfo() {
        return this.signRequestException;
    }
}
