
package net.felsing.client_cert.ejbca;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.2
 * 2017-05-15T16:18:08.012+02:00
 * Generated source version: 3.1.2
 */

@WebFault(name = "UnknownProfileTypeException", targetNamespace = "http://ws.protocol.core.ejbca.org/")
public class UnknownProfileTypeException_Exception extends Exception {
    
    private net.felsing.client_cert.ejbca.UnknownProfileTypeException unknownProfileTypeException;

    public UnknownProfileTypeException_Exception() {
        super();
    }
    
    public UnknownProfileTypeException_Exception(String message) {
        super(message);
    }
    
    public UnknownProfileTypeException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public UnknownProfileTypeException_Exception(String message, net.felsing.client_cert.ejbca.UnknownProfileTypeException unknownProfileTypeException) {
        super(message);
        this.unknownProfileTypeException = unknownProfileTypeException;
    }

    public UnknownProfileTypeException_Exception(String message, net.felsing.client_cert.ejbca.UnknownProfileTypeException unknownProfileTypeException, Throwable cause) {
        super(message, cause);
        this.unknownProfileTypeException = unknownProfileTypeException;
    }

    public net.felsing.client_cert.ejbca.UnknownProfileTypeException getFaultInfo() {
        return this.unknownProfileTypeException;
    }
}
