
package net.felsing.client_cert.ejbca;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.2
 * 2017-05-15T16:18:08.008+02:00
 * Generated source version: 3.1.2
 */

@WebFault(name = "WaitingForApprovalException", targetNamespace = "http://ws.protocol.core.ejbca.org/")
public class WaitingForApprovalException_Exception extends Exception {
    
    private net.felsing.client_cert.ejbca.WaitingForApprovalException waitingForApprovalException;

    public WaitingForApprovalException_Exception() {
        super();
    }
    
    public WaitingForApprovalException_Exception(String message) {
        super(message);
    }
    
    public WaitingForApprovalException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public WaitingForApprovalException_Exception(String message, net.felsing.client_cert.ejbca.WaitingForApprovalException waitingForApprovalException) {
        super(message);
        this.waitingForApprovalException = waitingForApprovalException;
    }

    public WaitingForApprovalException_Exception(String message, net.felsing.client_cert.ejbca.WaitingForApprovalException waitingForApprovalException, Throwable cause) {
        super(message, cause);
        this.waitingForApprovalException = waitingForApprovalException;
    }

    public net.felsing.client_cert.ejbca.WaitingForApprovalException getFaultInfo() {
        return this.waitingForApprovalException;
    }
}
